/*  username: ali_baba
    password: apriti sesamo (con lo spazio)
*/


CREATE TABLE tipiUtente (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomeTipo VARCHAR(5) UNIQUE NOT NULL
);

CREATE TABLE tipiPost (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomeTipo VARCHAR (15) UNIQUE
);

CREATE TABLE tipiDestinazione (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomeTipo VARCHAR (15) UNIQUE
);


CREATE TABLE utenti (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(32),
    cognome VARCHAR(32),
    email VARCHAR(32) UNIQUE,
    dataNascita VARCHAR(10),
    urlFotoProfilo VARCHAR(500),
    frasePresentazione VARCHAR(500),

    tipoUtente INTEGER NOT NULL,
    FOREIGN KEY (tipoUtente) REFERENCES tipiUtente(id),

    username VARCHAR(16) UNIQUE NOT NULL,
    password VARCHAR(16) NOT NULL   
);

CREATE TABLE amici (
    idUtente1 INTEGER,
    idUtente2 INTEGER,

    PRIMARY KEY (idUtente1, idUtente2),
    FOREIGN KEY (idUtente1) REFERENCES utenti(id),
    FOREIGN KEY (idUtente2) REFERENCES utenti(id)
);

    
CREATE TABLE gruppi (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(30) UNIQUE NOT NULL,
    urlIcona VARCHAR(500)
);


CREATE TABLE posts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    autore INTEGER,
    FOREIGN KEY (autore) REFERENCES utenti(id),

    contenuto VARCHAR(500),

    tipo INTEGER,
    FOREIGN KEY (tipo) REFERENCES tipiPost(id),

    attachedUrl VARCHAR(500),
    
    tipoDestinazione INTEGER,
    FOREIGN KEY (tipoDestinazione) REFERENCES tipiDestinazione(id),

    idUtenteDest INTEGER,
    FOREIGN KEY (idUtenteDest) REFERENCES utenti(id),

    idGruppoDest INTEGER,
    FOREIGN KEY (idGruppoDest) REFERENCES gruppi(id)
);



CREATE TABLE iscrizioniGruppi (
    idUtente INTEGER,
    idGruppo INTEGER,

    PRIMARY KEY (idUtente, idGruppo),
    FOREIGN KEY (idUtente) REFERENCES utenti(id),
    FOREIGN KEY (idGruppo) REFERENCES gruppi(id)
);







INSERT INTO tipiDestinazione (id, nomeTipo)
VALUES ( default, 'BACHECA' );
INSERT INTO tipiDestinazione (id, nomeTipo)
VALUES ( default, 'GRUPPO' );

INSERT INTO tipiUtente (id, nomeTipo)
VALUES ( default, 'ADMIN' );
INSERT INTO tipiUtente (id, nomeTipo)
VALUES ( default, 'USER' );

INSERT INTO tipiPost (id, nomeTipo)
VALUES ( default, 'TESTO' );
INSERT INTO tipiPost (id, nomeTipo)
VALUES ( default, 'IMMAGINE' );
INSERT INTO tipiPost (id, nomeTipo)
VALUES ( default, 'LINK' );





INSERT INTO gruppi ( id, nome, urlIcona)
VALUES ( default, 'Molgonfieristi', 'Assets/ICONS/molgonfieristi_icona.svg' );

INSERT INTO gruppi ( id, nome, urlIcona)
VALUES ( default, 'Ritardatari', 'Assets/ICONS/ritardatari_icona.svg' );




INSERT INTO utenti ( id, nome, cognome, email, dataNascita, urlFotoProfilo, frasePresentazione, tipoUtente, username, password )
VALUES ( default, 'Djanni', 'Gatto', 'djannigatto@gmail.com', '2010-10-10',
        'Assets/IMG/djanniprofilo.jpg', 'ciao a tutti, sono io, Djanni',
        2, 'DjG', '123' );

INSERT INTO utenti ( id, nome, cognome, email, dataNascita, urlFotoProfilo, frasePresentazione, tipoUtente, username, password )
VALUES ( default, 'Heavy', 'Breathing', 'cholansia@gmail.com', '2010-10-11',
        null, 'ciao, sono Heavy Breathing',
        1, 'HeavyBreathing', '123' );

INSERT INTO utenti ( id, nome, cognome, email, dataNascita, urlFotoProfilo, frasePresentazione, tipoUtente, username, password )
VALUES ( default, 'Gym', 'WorkOut', 'doIt@gmail.com', '2010-10-12',
        'Assets/IMG/siamese.jpg', 'ciao, sono GymWorkOut',
        1, 'GymWorkOut', '123' );

INSERT INTO utenti ( id, nome, cognome, email, dataNascita, urlFotoProfilo, frasePresentazione, tipoUtente, username, password )
VALUES ( default, 'Chao', 'Povery', 'r1tchb1tch@gmail.com', '2010-10-13',
        null, 'ciao, sono Chao Povery',
        1, 'ChaoPovery', '123' );

INSERT INTO utenti ( id, nome, cognome, email, dataNascita, urlFotoProfilo, frasePresentazione, tipoUtente, username, password )
VALUES ( default, 'Incompleto', 'Orrù', 'incompleto@gmail.com', '2010-10-14',
        null, 'ciao, sono incompleto; completami!',
        1, 'incompleto', 'sonoincompleto' );







INSERT INTO posts ( id, autore, contenuto, tipo, attachedUrl, tipoDestinazione, idUtenteDest, idGruppoDest)
VALUES ( default, 1, 'Ciao, miei schiavi. Datemi cibo! Adesso! Miaomiaomiaomiaomiao!', 1, null, 1, 1, null); 
        
INSERT INTO posts ( id, autore, contenuto, tipo, attachedUrl, tipoDestinazione, idUtenteDest, idGruppoDest)
VALUES ( default, 1, 'Ti mando una foto, ciao', 1,
         'https://68.media.tumblr.com/51942e1f788f7209ee0f6db7cfc5e0fb/tumblr_n37ycpbMZf1rkxod7o1_500.jpg',
        1, 2, null);

INSERT INTO posts ( id, autore, contenuto, tipo, attachedUrl, tipoDestinazione, idUtenteDest, idGruppoDest)
VALUES ( default, 2, 'Siete invitati all evento in molgonfiera di giovedì, ci vediamo lì, ciao', 2,
         'http://68.media.tumblr.com/fe7cd8c3cd98e15f1812430959c36b56/tumblr_myftmaNObo1sh9bnuo1_500.jpg',
        2, null, 1);

INSERT INTO posts ( id, autore, contenuto, tipo, attachedUrl, tipoDestinazione, idUtenteDest, idGruppoDest)
VALUES ( default, 3, 'Và tutti che bella questa pic', 2,
         'http://68.media.tumblr.com/11e0fa516c5c382765ef28af19a341d3/tumblr_mynfdmKYPa1rq3dyyo1_1280.jpg',
        2, null, 1);

INSERT INTO posts ( id, autore, contenuto, tipo, attachedUrl, tipoDestinazione, idUtenteDest, idGruppoDest)
VALUES ( default, 2, 'Ti mando una foto, ciao', 2,
         'https://68.media.tumblr.com/51942e1f788f7209ee0f6db7cfc5e0fb/tumblr_n37ycpbMZf1rkxod7o1_500.jpg',
        1, 1, null);

INSERT INTO posts ( id, autore, contenuto, tipo, attachedUrl, tipoDestinazione, idUtenteDest, idGruppoDest)
VALUES ( default, 1, 'Guardati questo link, ciao', 3,
         'https://68.media.tumblr.com/51942e1f788f7209ee0f6db7cfc5e0fb/tumblr_n37ycpbMZf1rkxod7o1_500.jpg',
        1, 2, null);      

INSERT INTO posts ( id, autore, contenuto, tipo, attachedUrl, tipoDestinazione, idUtenteDest, idGruppoDest)
VALUES ( default, 3, 'Forse anche a trenitalia interessa iscriversi a questo gruppo? Invitateli!', 2,
         'Assets/IMG/trenitalia_ritardo_post.jpg',
        2, null, 2); 

INSERT INTO posts ( id, autore, contenuto, tipo, attachedUrl, tipoDestinazione, idUtenteDest, idGruppoDest)
VALUES ( default, 1, 'Hahaha dedicato al mio amico Gym', 2,
         'Assets/IMG/trenitalia_ritardo_post.jpg',
        2, null, 2);                   
        
INSERT INTO posts ( id, autore, contenuto, tipo, attachedUrl, tipoDestinazione, idUtenteDest, idGruppoDest)
VALUES ( default, 1, 'Iscrivetevi!', 3,
         'codechef.com',
        2, null, 2);  
